apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

nameSuffix: -prod

images:
  - name: ciyex-ehr-ui
    newName: IMAGE_URL
    newTag: IMAGE_TAG

replicas:
  - name: ciyex-ehr-ui
    count: 2

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: ehr-ui-config
    literals:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://app.ciyex.com/api
