/**
 * Common FHIR resource paths for the field config editor.
 * Organized by resource type to help admins configure FHIR mappings.
 */

export interface FhirPathSuggestion {
  path: string;
  label: string;
  type: "string" | "date" | "datetime" | "code" | "quantity" | "boolean" | "reference" | "address";
}

/** Common FHIR R4 resource type suggestions. Users can type any resource name — this list is only for autocomplete hints. */
export const FHIR_RESOURCES = [
  // Administration
  "Patient",
  "Practitioner",
  "PractitionerRole",
  "Organization",
  "Location",
  "HealthcareService",
  "Endpoint",
  "RelatedPerson",
  "Person",
  "Group",
  // Scheduling
  "Appointment",
  "AppointmentResponse",
  "Schedule",
  "Slot",
  // Clinical - Summary
  "AllergyIntolerance",
  "Condition",
  "Procedure",
  "FamilyMemberHistory",
  "ClinicalImpression",
  "DetectedIssue",
  // Clinical - Diagnostics
  "Observation",
  "DiagnosticReport",
  "Specimen",
  "ImagingStudy",
  "Media",
  "MolecularSequence",
  "BodyStructure",
  // Clinical - Medications
  "MedicationRequest",
  "MedicationDispense",
  "MedicationAdministration",
  "MedicationStatement",
  "Medication",
  "Immunization",
  "ImmunizationRecommendation",
  // Clinical - Care Provision
  "CarePlan",
  "CareTeam",
  "Goal",
  "ServiceRequest",
  "NutritionOrder",
  "ReferralRequest",
  "RiskAssessment",
  "RequestGroup",
  // Clinical - Request & Response
  "DeviceRequest",
  "SupplyRequest",
  "SupplyDelivery",
  "CommunicationRequest",
  "Communication",
  "Task",
  // Documents & Composition
  "DocumentReference",
  "DocumentManifest",
  "Composition",
  "QuestionnaireResponse",
  "Questionnaire",
  "Consent",
  // Encounter
  "Encounter",
  "EpisodeOfCare",
  "Flag",
  // Financial - Billing
  "Claim",
  "ClaimResponse",
  "Coverage",
  "CoverageEligibilityRequest",
  "CoverageEligibilityResponse",
  "ExplanationOfBenefit",
  "Invoice",
  "PaymentReconciliation",
  "PaymentNotice",
  "Account",
  "ChargeItem",
  "Contract",
  "InsurancePlan",
  // Terminology
  "ValueSet",
  "CodeSystem",
  // Conformance
  "OperationOutcome",
  "Bundle",
  "Binary",
  "Basic",
  "List",
] as const;

/** Common patient search parameter per FHIR resource */
export const FHIR_PATIENT_SEARCH_PARAMS: Record<string, string> = {
  // Administration
  Patient: "",
  Practitioner: "",
  PractitionerRole: "",
  Organization: "",
  Location: "",
  HealthcareService: "",
  Endpoint: "",
  RelatedPerson: "patient",
  Person: "",
  Group: "",
  // Scheduling
  Appointment: "patient",
  AppointmentResponse: "patient",
  Schedule: "",
  Slot: "",
  // Clinical - Summary
  AllergyIntolerance: "patient",
  Condition: "subject",
  Procedure: "subject",
  FamilyMemberHistory: "patient",
  ClinicalImpression: "subject",
  DetectedIssue: "patient",
  // Clinical - Diagnostics
  Observation: "subject",
  DiagnosticReport: "subject",
  Specimen: "subject",
  ImagingStudy: "subject",
  Media: "subject",
  MolecularSequence: "patient",
  BodyStructure: "patient",
  // Clinical - Medications
  MedicationRequest: "patient",
  MedicationDispense: "patient",
  MedicationAdministration: "patient",
  MedicationStatement: "patient",
  Medication: "",
  Immunization: "patient",
  ImmunizationRecommendation: "patient",
  // Clinical - Care Provision
  CarePlan: "subject",
  CareTeam: "subject",
  Goal: "subject",
  ServiceRequest: "subject",
  NutritionOrder: "patient",
  ReferralRequest: "subject",
  RiskAssessment: "subject",
  RequestGroup: "subject",
  // Clinical - Request & Response
  DeviceRequest: "subject",
  SupplyRequest: "",
  SupplyDelivery: "patient",
  CommunicationRequest: "subject",
  Communication: "subject",
  Task: "",
  // Documents & Composition
  DocumentReference: "subject",
  DocumentManifest: "subject",
  Composition: "subject",
  QuestionnaireResponse: "subject",
  Questionnaire: "",
  Consent: "patient",
  // Encounter
  Encounter: "subject",
  EpisodeOfCare: "patient",
  Flag: "patient",
  // Financial - Billing
  Claim: "patient",
  ClaimResponse: "patient",
  Coverage: "beneficiary",
  CoverageEligibilityRequest: "patient",
  CoverageEligibilityResponse: "patient",
  ExplanationOfBenefit: "patient",
  Invoice: "subject",
  PaymentReconciliation: "",
  PaymentNotice: "",
  Account: "subject",
  ChargeItem: "subject",
  Contract: "",
  InsurancePlan: "",
  // Terminology
  ValueSet: "",
  CodeSystem: "",
  // Conformance
  OperationOutcome: "",
  Bundle: "",
  Binary: "",
  Basic: "subject",
  List: "subject",
};

export type FhirResourceType = (typeof FHIR_RESOURCES)[number];

export const FHIR_PATH_SUGGESTIONS: Record<string, FhirPathSuggestion[]> = {
  Patient: [
    { path: "name[0].given[0]", label: "First Name", type: "string" },
    { path: "name[0].family", label: "Last Name", type: "string" },
    { path: "name[0].given[1]", label: "Middle Name", type: "string" },
    { path: "birthDate", label: "Date of Birth", type: "date" },
    { path: "gender", label: "Gender", type: "code" },
    { path: "telecom[0].value", label: "Phone", type: "string" },
    { path: "telecom[2].value", label: "Email", type: "string" },
    { path: "address[0]", label: "Address", type: "address" },
    { path: "identifier[0].value", label: "MRN", type: "string" },
    { path: "maritalStatus.coding[0].code", label: "Marital Status", type: "code" },
    { path: "communication[0].language.coding[0].code", label: "Language", type: "code" },
    { path: "active", label: "Active Status", type: "boolean" },
    { path: "generalPractitioner[0].reference", label: "Primary Provider", type: "reference" },
    { path: "contact[0].name.text", label: "Emergency Contact Name", type: "string" },
    { path: "contact[0].telecom[0].value", label: "Emergency Contact Phone", type: "string" },
  ],
  Observation: [
    { path: "effectiveDateTime", label: "Date/Time", type: "datetime" },
    { path: "status", label: "Status", type: "code" },
    { path: "note[0].text", label: "Notes", type: "string" },
    { path: "component.where(code.coding.code='29463-7').valueQuantity.value", label: "Weight", type: "quantity" },
    { path: "component.where(code.coding.code='8302-2').valueQuantity.value", label: "Height", type: "quantity" },
    { path: "component.where(code.coding.code='8480-6').valueQuantity.value", label: "BP Systolic", type: "quantity" },
    { path: "component.where(code.coding.code='8462-4').valueQuantity.value", label: "BP Diastolic", type: "quantity" },
    { path: "component.where(code.coding.code='8867-4').valueQuantity.value", label: "Pulse", type: "quantity" },
    { path: "component.where(code.coding.code='9279-1').valueQuantity.value", label: "Respiration", type: "quantity" },
    { path: "component.where(code.coding.code='8310-5').valueQuantity.value", label: "Temperature", type: "quantity" },
    { path: "component.where(code.coding.code='2708-6').valueQuantity.value", label: "O2 Saturation", type: "quantity" },
    { path: "component.where(code.coding.code='39156-5').valueQuantity.value", label: "BMI", type: "quantity" },
  ],
  AllergyIntolerance: [
    { path: "code.text", label: "Allergen Name", type: "string" },
    { path: "clinicalStatus.coding[0].code", label: "Clinical Status", type: "code" },
    { path: "criticality", label: "Criticality/Severity", type: "code" },
    { path: "reaction[0].manifestation[0].text", label: "Reaction", type: "string" },
    { path: "onsetDateTime", label: "Onset Date", type: "date" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
  MedicationRequest: [
    { path: "medicationCodeableConcept.text", label: "Medication Name", type: "string" },
    { path: "status", label: "Status", type: "code" },
    { path: "dosageInstruction[0].text", label: "Dosage", type: "string" },
    { path: "dosageInstruction[0].patientInstruction", label: "Instructions", type: "string" },
    { path: "requester.display", label: "Prescriber", type: "reference" },
    { path: "authoredOn", label: "Date Issued", type: "datetime" },
  ],
  Immunization: [
    { path: "vaccineCode.coding[0].code", label: "Vaccine Code (CVX)", type: "code" },
    { path: "occurrenceDateTime", label: "Date Administered", type: "datetime" },
    { path: "manufacturer.display", label: "Manufacturer", type: "string" },
    { path: "lotNumber", label: "Lot Number", type: "string" },
    { path: "expirationDate", label: "Expiration Date", type: "date" },
    { path: "route.text", label: "Route", type: "string" },
    { path: "site.text", label: "Site", type: "string" },
    { path: "doseQuantity.value", label: "Dose Amount", type: "quantity" },
    { path: "performer[0].actor.display", label: "Administrator", type: "string" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
  Encounter: [
    { path: "class.code", label: "Encounter Type", type: "code" },
    { path: "reasonCode[0].text", label: "Reason", type: "string" },
    { path: "status", label: "Status", type: "code" },
    { path: "period.start", label: "Start Date", type: "datetime" },
    { path: "period.end", label: "End Date", type: "datetime" },
    { path: "participant[0].individual.reference", label: "Provider", type: "reference" },
  ],
  Condition: [
    { path: "code.text", label: "Condition Name", type: "string" },
    { path: "code.coding[0].code", label: "ICD-10 Code", type: "code" },
    { path: "clinicalStatus.coding[0].code", label: "Clinical Status", type: "code" },
    { path: "severity.coding[0].code", label: "Severity", type: "code" },
    { path: "onsetDateTime", label: "Onset Date", type: "date" },
    { path: "abatementDateTime", label: "Resolved Date", type: "date" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
  Procedure: [
    { path: "code.text", label: "Procedure Name", type: "string" },
    { path: "code.coding[0].code", label: "CPT Code", type: "code" },
    { path: "status", label: "Status", type: "code" },
    { path: "performedDateTime", label: "Date Performed", type: "datetime" },
    { path: "performer[0].actor.reference", label: "Performer", type: "reference" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
  DiagnosticReport: [
    { path: "code.coding[0].code", label: "Test Code (LOINC)", type: "code" },
    { path: "code.text", label: "Test Name", type: "string" },
    { path: "status", label: "Status", type: "code" },
    { path: "effectiveDateTime", label: "Collection Date", type: "datetime" },
    { path: "issued", label: "Result Date", type: "datetime" },
    { path: "conclusion", label: "Conclusion", type: "string" },
  ],
  Coverage: [
    { path: "payor[0].display", label: "Insurance Company", type: "reference" },
    { path: "class[0].value", label: "Plan Name", type: "string" },
    { path: "class[1].value", label: "Group Number", type: "string" },
    { path: "subscriberId", label: "Subscriber ID", type: "string" },
    { path: "subscriber.display", label: "Subscriber Name", type: "string" },
    { path: "relationship.coding[0].code", label: "Relationship", type: "code" },
    { path: "identifier[0].value", label: "Policy Number", type: "string" },
    { path: "period.start", label: "Effective From", type: "date" },
    { path: "period.end", label: "Effective To", type: "date" },
    { path: "status", label: "Status", type: "code" },
  ],
  DocumentReference: [
    { path: "description", label: "Title", type: "string" },
    { path: "type.coding[0].code", label: "Document Type", type: "code" },
    { path: "status", label: "Status", type: "code" },
    { path: "date", label: "Document Date", type: "datetime" },
    { path: "author[0].reference", label: "Author", type: "reference" },
    { path: "content[0].attachment.url", label: "Attachment URL", type: "string" },
  ],
  Claim: [
    { path: "item[0].servicedDate", label: "Service Date", type: "date" },
    { path: "item[0].productOrService.coding[0].code", label: "CPT Code", type: "code" },
    { path: "diagnosis[0].diagnosisCodeableConcept.coding[0].code", label: "Diagnosis Code", type: "code" },
    { path: "provider.reference", label: "Rendering Provider", type: "reference" },
    { path: "item[0].unitPrice.value", label: "Charge Amount", type: "quantity" },
    { path: "status", label: "Status", type: "code" },
  ],
  CarePlan: [
    { path: "title", label: "Plan Title", type: "string" },
    { path: "status", label: "Status", type: "code" },
    { path: "intent", label: "Intent", type: "code" },
    { path: "period.start", label: "Start Date", type: "date" },
    { path: "period.end", label: "End Date", type: "date" },
    { path: "description", label: "Description", type: "string" },
    { path: "goal[0].reference", label: "Goal", type: "reference" },
    { path: "activity[0].detail.description", label: "Activity", type: "string" },
  ],
  RelatedPerson: [
    { path: "name[0].given[0]", label: "First Name", type: "string" },
    { path: "name[0].family", label: "Last Name", type: "string" },
    { path: "relationship[0].coding[0].code", label: "Relationship", type: "code" },
    { path: "telecom[0].value", label: "Phone", type: "string" },
    { path: "telecom[1].value", label: "Email", type: "string" },
    { path: "address[0]", label: "Address", type: "address" },
  ],
  ImagingStudy: [
    { path: "modality[0].code", label: "Modality", type: "code" },
    { path: "description", label: "Description", type: "string" },
    { path: "started", label: "Study Date", type: "datetime" },
    { path: "status", label: "Status", type: "code" },
    { path: "numberOfSeries", label: "Number of Series", type: "quantity" },
    { path: "numberOfInstances", label: "Number of Images", type: "quantity" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
  Goal: [
    { path: "description.text", label: "Goal Description", type: "string" },
    { path: "lifecycleStatus", label: "Status", type: "code" },
    { path: "priority.coding[0].code", label: "Priority", type: "code" },
    { path: "startDate", label: "Start Date", type: "date" },
    { path: "target[0].dueDate", label: "Target Date", type: "date" },
    { path: "note[0].text", label: "Notes", type: "string" },
  ],
};

export const FIELD_TYPES = [
  { value: "text", label: "Text" },
  { value: "textarea", label: "Text Area" },
  { value: "number", label: "Number" },
  { value: "select", label: "Dropdown" },
  { value: "multiselect", label: "Multi-Select" },
  { value: "radio", label: "Radio Buttons" },
  { value: "checkbox", label: "Checkbox" },
  { value: "boolean", label: "Toggle" },
  { value: "date", label: "Date" },
  { value: "datetime", label: "Date + Time" },
  { value: "phone", label: "Phone" },
  { value: "email", label: "Email" },
  { value: "lookup", label: "Lookup (API)" },
  { value: "coded", label: "Coded Value" },
  { value: "quantity", label: "Quantity + Unit" },
  { value: "file", label: "File Upload" },
  { value: "group", label: "Section Divider" },
  { value: "computed", label: "Computed (Read-only)" },
  { value: "address", label: "Address" },
] as const;
