apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-ehr-ui
  labels:
    app: ciyex-ehr-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciyex-ehr-ui
  template:
    metadata:
      labels:
        app: ciyex-ehr-ui
    spec:
      containers:
        - name: ciyex-ehr-ui
          image: ciyex-ehr-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: NODE_ENV
              value: "production"
